import Foundation

/// Maps a phrase spoken by the tempo coach (as produced by `CuePlanner`/`CoachingPolicy`) to one or
/// more pre-recorded audio variants, so the same correction doesn't sound identical every time.
/// Pure lookup/selection logic, kept free of AVFoundation and Bundle so it can be unit tested; the
/// actual clips are generated by `scripts/generate_voice_bank.py` and played by `BankedCoachVoice`.
public struct CoachPhraseBank: Sendable {
    public struct Variant: Sendable, Equatable {
        public var text: String
        public var file: String

        public init(text: String, file: String) {
            self.text = text
            self.file = file
        }
    }

    private let variantsByPhrase: [String: [Variant]]

    public init(variantsByPhrase: [String: [Variant]]) {
        self.variantsByPhrase = variantsByPhrase
    }

    public static let empty = CoachPhraseBank(variantsByPhrase: [:])

    public func variants(for phrase: String) -> [Variant] {
        variantsByPhrase[phrase] ?? []
    }

    /// Picks a recorded variant for `phrase`, considering only ones `exists` confirms are actually
    /// generated (the manifest can list a phrase before its clip exists), and avoiding `excluding`
    /// when another choice is available so the same clip isn't heard twice in a row. `nil` means no
    /// usable recording for this phrase — the caller should fall back to the system voice.
    public func pickVariant(for phrase: String, excluding: String? = nil, exists: (String) -> Bool) -> Variant? {
        let available = variants(for: phrase).filter { exists($0.file) }
        guard !available.isEmpty else { return nil }
        let preferred = available.count > 1 ? available.filter { $0.file != excluding } : available
        return preferred.randomElement() ?? available.randomElement()
    }
}

extension CoachPhraseBank {
    private struct Manifest: Decodable {
        struct RawVariant: Decodable {
            let text: String
            let file: String
        }
        let phrases: [String: [RawVariant]]
    }

    /// Loads `voice_manifest.json` from `bundle`. An empty bank (full fallback to the system voice)
    /// when the manifest is missing or malformed — the normal state before the generation script
    /// has been run at least once.
    public static func loadBundled(from bundle: Bundle) -> CoachPhraseBank {
        guard let url = bundle.url(forResource: "voice_manifest", withExtension: "json"),
            let data = try? Data(contentsOf: url)
        else { return .empty }
        return parse(data) ?? .empty
    }

    static func parse(_ data: Data) -> CoachPhraseBank? {
        guard let manifest = try? JSONDecoder().decode(Manifest.self, from: data) else { return nil }
        let variants = manifest.phrases.mapValues { $0.map { Variant(text: $0.text, file: $0.file) } }
        return CoachPhraseBank(variantsByPhrase: variants)
    }
}
